### ISSUE TITLE
片头动画基本上还全是乱码

### ISSUE THREAD

**Issue by crashGG** [RickyL1213/YumeMaboroshiNoGotoku-CN#1]
![如梦似幻 (繁)(全对话 部分菜单)(RickyL1213)-220320-075813](https://user-images.githubusercontent.com/80488411/159148919-2801cad2-017a-4e92-8c06-67aab14218ae.png)

**Comment by RickyL1213** [comment]
这个目前无解。跟很多其他SFC汉化一样。菜单和开场的字比较难弄。

不过这里提供了开场两短文字的DeepL翻译：
https://github.com/RickyL1213/YumeMaboroshiNoGotoku-CN/blob/698ccfb7e0d6ffb9cb8fe3c061f4266a3a9210e0/openSceneText.txt
